Backport Evergreen config for host osx-1010-compass

diff --git a/.evergreen.yml b/.evergreen.yml
--- a/.evergreen.yml
+++ b/.evergreen.yml
@@ -12,7 +12,7 @@ variables:
 # function "save release variants" is conditional on the following
 # -> all except ubuntu
 - &save_release_variants
-  - osx-108
+  - osx-1010
   - windows-64
 
 
@@ -55,6 +55,7 @@ functions:
           --url "http://mongodb-dx-public.s3.amazonaws.com/evergreen-deps/${fetch_npm_tarball}"
         cd .deps
         tar xzf ${fetch_npm_tarball} --strip-components=1
+        chmod +x npm.cmd || true
 
   "npm install" :
     command: shell.exec
@@ -62,25 +63,28 @@ functions:
       working_dir: src
       script: |
         set -ev
+        export CI=1
+        export EVERGREEN=1
         export PATH="${node_path}:$PATH"
         ls -alh ${node_path}
-        test -n "${add_environment|}" && export ${add_environment|}
+        test -n '${add_env_appdata|}' && export APPDATA='${add_env_appdata|}'
         ${npm|npm} version --json
-        ${npm|npm} config set loglevel error
-        ${npm|npm} config -g list
-        which -a npm
-        node -p process.env
+        # less chatty installs: "--depth 0" reduces detail of "npm ls" tree output
+        export NPM_CONFIG_DEPTH=0
+        export NPM_CONFIG_LOGLEVEL=error
         ${npm|npm} install
+        # INT-1081 Attach parseable log of installed packages.
+        # Don't allow it to fail build.
+        ${npm|npm} ls --depth=Infinity --json=true > npm_install.json || true
 
   # For Windows: retrieve a fake "signtool.exe" which proxies to notary-service,
   # and remove the real one from our path. Must run after "npm install"
   "fetch signtool" : &fetch_signtool
     command: shell.exec
-    build_variants:
-      - windows-64
     params:
       working_dir: src
       script: |
+        set -ev
         curl -fs \
           -o "signtool.exe" \
           --url "https://s3.amazonaws.com/boxes.10gen.com/build/signtool.exe"
@@ -98,15 +102,65 @@ functions:
       working_dir: src
       script: |
         set -ev
+        rm -f ~/compass_build.log
+        cat <<EOF_BUILD_SH > ~/compass_build.sh
+        set -ev
+        cd $(pwd)
         export PATH="${node_path}:$PATH"
-        export CI=1 EVERGREEN=1
+        export CI=1
+        export EVERGREEN=1
+        export EVERGREEN_PROJECT=${project}
         export NOTARY_URL="http://notary-service.build.10gen.cc:5000"
         export NOTARY_AUTH_TOKEN="${signing_auth_token}"
         export NOTARY_SIGNING_KEY="${signing_key_name}"
         export NOTARY_SIGNING_COMMENT="Evergreen project mongodb/compass ${revision} - ${build_variant} - ${branch_name}"
         export SIGNTOOL_PARAMS="yes"
-        test -n "${add_environment|}" && export ${add_environment|}
+        test -n '${add_env_appdata|}' && export APPDATA='${add_env_appdata|}'
+
+        # The env script is a special built-in command that can be used to
+        # list environment variables that will be available to the
+        # script at runtime.
+        # @see https://docs.npmjs.com/cli/run-script
+        ${npm|npm} run env
+
+        # Run static analysis on code and project configuration
+        ${npm|npm} run check
+
         ${npm|npm} run ci
+
+        EOF_BUILD_SH
+        #
+        # Use ".", not "source" below to read script. Required for /bin/sh on Ubuntu.
+        #
+        if [ -n "${build_via_local_tunnel|}" ]
+        then
+          ssh -v -p 2222 localhost ". compass_build.sh"
+        else
+          . ~/compass_build.sh
+        fi
+
+  "test_ssh_localhost" :
+    command: shell.exec
+    params:
+      working_dir: src
+      script: |
+        set -ev
+        if [ -n "${build_via_local_tunnel|}" ]
+        then
+          ssh -p 2222 localhost "echo SSH_LOCALHOST_TEST_OK"
+        fi
+
+  "save npm_install.json":
+    command: s3.put
+    params:
+      aws_key: ${aws_key}
+      aws_secret: ${aws_secret}
+      local_file: "src/npm_install.json"
+      remote_file: "${project}/${build_variant}/${revision}/npm_install.json"
+      bucket: mciuploads
+      permissions: public-read
+      content_type: application/json
+      display_name: "npm_install.json"
 
   "save release":
     command: s3.put
@@ -116,7 +170,7 @@ functions:
       aws_key: ${aws_key}
       aws_secret: ${aws_secret}
       local_file: "src/dist/${installer_filename}"
-      remote_file: "mongodb-compass-master/${build_variant}/${revision}/${installer_filename}"
+      remote_file: "${project}/${build_variant}/${revision}/${installer_filename}"
       bucket: mciuploads
       permissions: public-read
       content_type: ${installer_content_type|application/octet-stream}
@@ -151,11 +205,17 @@ tasks:
 - name: compile
   depends_on: []
   commands:
+  - func: "test_ssh_localhost"
+    variants:
+      - osx-1010
   - func: "fetch source"
   - func: "fetch npm tarball"
   - func: "npm install"
   - func: "fetch signtool"
+    variants:
+      - windows-64
   - func: "build"
+  - func: "save npm_install.json"
   - func: "save release"
 
 # Define shortcut for use below
@@ -168,12 +228,13 @@ variables:
 #######################################
 
 buildvariants:
-- name: osx-108
-  display_name: OS X 10.8
+- name: osx-1010
+  display_name: OS X 10.10
   modules: ~
   run_on:
-  - "osx-108"
+  - "osx-1010-compass"
   expansions:
+    build_via_local_tunnel: true
     fetch_npm_tarball: node-v4.2.2-npm-3.3.12-darwin-x64.tgz
     node_path: "$(pwd)/.deps/bin"
     installer_content_type: "application/x-apple-diskimage"
@@ -193,7 +254,7 @@ buildvariants:
     installer_content_type: "application/octet-stream"
     installer_filename: "MongoDBCompassSetup.exe"
     num_cores: $(grep -c ^processor /proc/cpuinfo)
-    add_environment: APPDATA=C:\\Users\\Administrator\\
+    add_env_appdata: Z:\
   tasks:
     *all_tasks
 
