chore: fix CI badge in readme (#318)

diff --git a/packages/compass-crud/.github/workflows/run-tests.yml b/packages/compass-crud/.github/workflows/run-tests.yml
--- a/packages/compass-crud/.github/workflows/run-tests.yml
+++ b/packages/compass-crud/.github/workflows/run-tests.yml
@@ -37,7 +37,7 @@ jobs:
             ${{ runner.os }}-
       
       - name: Install Required OS Packages
-        run: sudo apt-get -y install libkrb5-dev libsecret-1-dev
+        run: sudo apt-get -y install libkrb5-dev libsecret-1-dev net-tools
       
       - name: Install NPM Packages
         run: npm install
@@ -46,4 +46,16 @@ jobs:
         run: |
           npm run check
           npm run test
+          while true; do \
+            MATCH="$(sudo netstat -tlnp | grep 27018 || true)"; \
+            if [[ "$MATCH" == "" ]]; then echo "mongod exited..."; break; fi; \
+            echo "$MATCH"; \
+            echo "mongod still up..."; \
+            PID="$(echo $MATCH | awk '{print $7}' | cut -f1 -d'/')"; \
+            if [[ "$PID" == "" ]]; then echo "failed to find PID"; break; fi; \
+            echo "sudo killing -9 $PID..."; \
+            sudo kill -9 $PID; \
+            echo "... killed?!"; \
+            sleep 3; \
+          done
           npm run test:karma
